In [1]:
import matplotlib.pyplot as plt
import numpy as np
import yfinance as yf
import pandas as pd

In [2]:
i = "Appl"
indicators = ["Open","Close"]
[i + "_" + str(s) for s in indicators]

['Appl_Open', 'Appl_Close']

In [3]:
def get_stock_prices(stocks, indicators):
    df = pd.DataFrame()
    for i in stocks:  # ["AAPL","MSI","SBUX"]:
        stock_df = yf.download(i, start="2015-01-01", end="2020-03-20").copy()
        stock_df = stock_df[indicators].copy()  # stock_df[["Open","Close"]]
        stock_df["Diff"] = stock_df["Close"] - stock_df["Open"]
        print(stock_df.head())
        stock_df.drop(columns=["Open"],inplace =True)
        colnames = [s + "_" + i for s in stock_df.columns]
        print(colnames)
        stock_df.columns = colnames
        df = pd.concat([df, stock_df], axis=1)
    return df


data_df = get_stock_prices(["AAPL", "MSI", "SBUX"], ["Open", "Close"])
data_df = data_df[sorted(data_df.columns)]
print(data_df.head())

[*********************100%***********************]  1 of 1 completed
                 Open      Close      Diff
Date
2015-01-02  27.847500  27.332500 -0.514999
2015-01-05  27.072500  26.562500 -0.510000
2015-01-06  26.635000  26.565001 -0.070000
2015-01-07  26.799999  26.937500  0.137501
2015-01-08  27.307501  27.972500  0.664999
['Close_AAPL', 'Diff_AAPL']
[*********************100%***********************]  1 of 1 completed
                 Open      Close      Diff
Date
2015-01-02  67.540001  66.510002 -1.029999
2015-01-05  66.239998  65.059998 -1.180000
2015-01-06  65.000000  64.510002 -0.489998
2015-01-07  65.000000  64.430000 -0.570000
2015-01-08  64.910004  65.430000  0.519997
['Close_MSI', 'Diff_MSI']
[*********************100%***********************]  1 of 1 completed
                 Open      Close      Diff
Date
2015-01-02  41.064999  40.720001 -0.344997
2015-01-05  40.070000  39.939999 -0.130001
2015-01-06  40.169998  39.615002 -0.554996
2015-01-07  39.875000  40.590000  0.715000
2015-01-08  41.165001  41.244999  0.079998
['Close_SBUX', 'Diff_SBUX']
            Close_AAPL  Close_MSI  Close_SBUX  Diff_AAPL  Diff_MSI  Diff_SBUX
Date
2015-01-02   27.332500  66.510002   40.720001  -0.514999 -1.029999  -0.344997
2015-01-05   26.562500  65.059998   39.939999  -0.510000 -1.180000  -0.130001
2015-01-06   26.565001  64.510002   39.615002  -0.070000 -0.489998  -0.554996
2015-01-07   26.937500  64.430000   40.590000   0.137501 -0.570000   0.715000
2015-01-08   27.972500  65.430000   41.244999   0.664999  0.519997   0.079998

In [4]:
data_df.to_csv("3_stocks_diff.csv",index=False)

In [4]:
apple_df[["Open","Close"]]

                 Open      Close
Date
2020-02-03  76.074997  77.165001
2020-02-04  78.827499  79.712502
2020-02-05  80.879997  80.362503
2020-02-06  80.642502  81.302498
2020-02-07  80.592499  80.007500
2020-02-10  78.544998  80.387497
2020-02-11  80.900002  79.902496
2020-02-12  80.367500  81.800003
2020-02-13  81.047501  81.217499
2020-02-14  81.184998  81.237503
2020-02-18  78.839996  79.750000
2020-02-19  80.000000  80.904999
2020-02-20  80.657501  80.074997
2020-02-21  79.654999  78.262497
2020-02-24  74.315002  74.544998
2020-02-25  75.237503  72.019997
2020-02-26  71.632500  73.162498
2020-02-27  70.275002  68.379997
2020-02-28  64.315002  68.339996
2020-03-02  70.570000  74.702499
2020-03-03  75.917503  72.330002
2020-03-04  74.110001  75.684998
2020-03-05  73.879997  73.230003
2020-03-06  70.500000  72.257500
2020-03-09  65.937500  66.542503
2020-03-10  69.285004  71.334999
2020-03-11  69.347504  68.857498
2020-03-12  63.985001  62.057499
2020-03-13  66.222504  69.492500
2020-03-16  60.487499  60.552502
2020-03-17  61.877499  63.215000
2020-03-18  59.942501  61.667500
2020-03-19  61.847500  61.195000